debug: true
server:
  port: 8080
spring:
  cloud:
    stream:
      bindings:
        apptRequestIn:
          destination: appointments
          group: pipeline
          content-type: application/json
        apptRequestOut:
          destination: appointments
          content-type: application/json
        docRequestIn:
          destination: docs
          group: pipeline
          content-type: application/json
        docRequestOut:
          destination: docs
          content-type: application/json
        archiveRequestIn:
          destination: archives
          group: pipeline
          content-type: application/json
        archiveRequestOut:
          destination: archives
          content-type: application/json
        summaryRequestIn:
          destination: summaries
          group: pipeline
          content-type: application/json
        summaryRequestOut:
          destination: summaries
          content-type: application/json
